/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_fudan_ringbell_media_MusicConverter */

#ifndef _Included_edu_fudan_ringbell_media_MusicConverter
#define _Included_edu_fudan_ringbell_media_MusicConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_fudan_ringbell_media_MusicConverter
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_fudan_ringbell_media_MusicConverter_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
